pipelineType: python
runTests: true
testCommand: "pytest test.py"
deployUponTestSuccess: true
deploymentEnvironment: "staging"

#pipelineType: java
#runTests: true
#testCommand: mvn test
#deployUponTestSuccess: true
#deploymentEnvironment: staging

